stages:
  - sync

sync-to-github:
  stage: sync
  image: alpine:latest
  only:
    - main  # or your desired branch
  script:
    - apk add --no-cache git openssh
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/goris31records/vscodeConfig.git
    - git push --force github HEAD:main
