stages:
  - sync

sync-to-github:
  stage: sync
  image: alpine:latest
  only:
    - main
  script:
    - apk add --no-cache git openssh
    - git config --global user.email "goris31records@gmail.com"
    - git config --global user.name "Wesly Goris"
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/goris31records/vscodeConfig.git
    - git push --force github HEAD:main
